substitutions:
  mac_address: "AA:BB:CC:DD:EE:FF"

  service_uuid: "0000ffe0-0000-1000-8000-00805f9b34fb"
  char_fff1_uuid: "0000ffe1-0000-1000-8000-00805f9b34fb"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

ble_client:
  - mac_address: ${mac_address}
    id: heater_ble
    on_connect:
      then:
        - logger.log: "🔗 Connected to heater"
    on_disconnect:
      then:
        - logger.log: "🔗 Disconnected from heater"

interval:
  - interval: 5s
    then:
      - script.execute: request_data

globals:
  - id: heater_power
    type: int
    restore_value: no
    initial_value: '0'
  - id: heater_temperature
    type: int
    restore_value: no
    initial_value: '0'
  - id: heater_setpoint
    type: int
    restore_value: no
    initial_value: '0'

# =========================
# Sensors
# =========================
sensor:
  - platform: ble_client
    type: characteristic
    id: my_ble_sensor
    internal: true
    ble_client_id: heater_ble
    service_uuid: ${service_uuid}
    characteristic_uuid: ${char_fff1_uuid}
    notify: true
    lambda: |-
      char compareline[64];

      snprintf(
        compareline,
        sizeof(compareline),
        "%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d",
        x[1],x[2],x[3],x[4],x[5],x[8],x[9],x[10],x[14],x[16],x[17],x[18]
      );

      static std::string prev_compare;
      std::string current_compare(compareline);

      static const char* const states[] = {
        "Idle", "Self test running", "Ignition", "Heating", "Shutting down"
      };

      if (x[0] == 170) {

        if (current_compare != prev_compare) {
          ESP_LOGD(
            "Vevor_8kW_BLE", 
            "Power: %d | Status: %d | Mode: %d | SP: %3d | Speed: %2d | BT: %3d | RT: %2d | Err: %2d",
            x[3],        x[5],        x[8],      x[9],     x[10],       x[13],    x[15],    x[17]
          );
      
          ESP_LOGD(
            "Vevor_8kW_BLE", 
            "Head:%03d|?:%03d|?:%d|?:%d|BT_M:%d|RT_M:%d|?:%d|?:%03d",
            x[0],      x[1],  x[2],x[4],x[14],   x[16], x[18],x[19]
          );
      
      
          id(heater_setpoint) = x[9];
      
          id(heater_debug_bit_1).publish_state(x[1]);
          id(heater_debug_bit_2).publish_state(x[2]);
          id(heater_debug_bit_4).publish_state(x[4]);
          id(heater_debug_bit_14).publish_state(x[14]);
          id(heater_debug_bit_16).publish_state(x[16]);
          id(heater_debug_bit_18).publish_state(x[18]);
          id(heater_debug_bit_19).publish_state(x[19]);
      
          prev_compare = current_compare;
        }
      
        id(heater_burner_state).publish_state(x[3] > 0);
      
        // Set States
        if (x[5] < sizeof(states)/sizeof(states[0])) {
          id(heater_burner_status).publish_state(states[x[5]]);
        } else {
          ESP_LOGE("Vevor_8kW_BLE", "Received state does not match known possible states: %02d", x[5]);
        }

        id(heater_burner_altitude).publish_state(((x[7])<<8)|x[6]);
      
        // Set mode string in a separate variable
        const char* mode_str = (x[8] == 2) ? "Temperature" : "Power";

        if (id(heater_control_mode).current_option() != mode_str) {
          id(heater_control_mode).publish_state(mode_str);
        }

        id(heater_target_mode).publish_state(mode_str);
        
        if (std::strcmp(mode_str, "Temperature") == 0) {
          id(heater_control_target_power).publish_state(NAN);
      
          float target_value = x[9];
      
          if (target_value >= 0 && target_value <= 36) {
            id(heater_control_target_temperature).publish_state((float)target_value);
          }

          id(heater_target_temperature).publish_state((int)target_value);
          id(heater_target_power).publish_state(NAN);
        } 
        else {
          id(heater_control_target_temperature).publish_state(NAN);
          id(heater_control_target_power).publish_state((float)x[9] * 10);
      
          id(heater_target_temperature).publish_state(NAN);
          id(heater_target_power).publish_state(x[9] * 10);
        }
      
        id(heater_speed).publish_state(std::to_string((int)x[10] + 1));
        id(heater_battery_voltage).publish_state((((x[12])<<8)|x[11]) / 10.0);
        id(heater_burner_temperature).publish_state((int16_t)(((uint8_t)x[14])<<8)|x[13]);
        
        float room_temperature = (int16_t)(((uint8_t)x[16] << 8) | x[15]);
        
        id(heater_room_temperature).publish_state(room_temperature);
        id(heater_burner_error_code).publish_state(std::to_string(x[17]));
      
        if(!id(heater_burner_state).state){
          id(heater_control_target_temperature).publish_state(NAN);
          id(heater_control_target_power).publish_state(NAN);
          
          id(heater_burner_altitude).publish_state(NAN);
          id(heater_battery_voltage).publish_state(NAN);
          id(heater_target_power).publish_state(NAN);
          id(heater_target_temperature).publish_state(NAN);
        }
      
        std::string status = id(heater_burner_status).state;
      
        if ("Shutting down" == status) {
          id(heater_speed).publish_state("0");
        }
        else if ("Idle" == status) {
          id(heater_speed).publish_state("0");
          id(heater_target_power).publish_state(0);
        }
      }
      return 0;

script:
  # Interface
  - id: !extend heater_turn_on
    then:
      - if:
          condition:
            lambda: |-
              return !id(heater_burner_state).state;
          then:
            - lambda: |-
                ESP_LOGI("Vevor_8kW_BLE", "Turning Heater On");
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: ${service_uuid}
                characteristic_uuid: ${char_fff1_uuid}
                value: [0xAA, 0x55, 0x0C, 0x22, 0x03, 0x01, 0x00, 0x32]
            - delay: 200ms
            - script.execute: request_data

  - id: !extend heater_turn_off
    then:
      - if:
          condition:
            lambda: |-
              return id(heater_burner_state).state;
          then:
            - lambda: |-
                ESP_LOGI("Vevor_8kW_BLE", "Turning Heater Off");
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: ${service_uuid}
                characteristic_uuid: ${char_fff1_uuid}
                value: [0xAA, 0x55, 0x0C, 0x22, 0x03, 0x00, 0x00, 0x31]
            - delay: 200ms
            - script.execute: request_data

  - id: !extend heater_set_power
    then:
      - if:
          condition:
            lambda: |-
              return percentage > 0;
          then:
            - lambda: |-
                if(percentage != id(heater_power)){
                  ESP_LOGI("Vevor_8kW_BLE", "Setting Heater Power to %d%%", percentage);
                }
            - script.execute: heater_turn_on
            - script.execute: set_heater_mode_power
            - lambda: |-
                id(heater_power) = percentage;

                int level = static_cast<int>(roundf(percentage / 10.0f));
                if (level < 0) level = 0;
                if (level > 10) level = 10;

                id(heater_set_target_value).execute(level);
          else:
            - script.execute: heater_turn_off

  - id: !extend heater_set_temperature
    then:
      - if:
          condition:
            - lambda: |-
                return roundf(temperature) != id(heater_temperature);
          then:
          - script.execute: heater_turn_on
          - script.execute: set_heater_mode_temperature
          - lambda: |-
              int temp_int = static_cast<int>(roundf(temperature));
              id(heater_temperature) = temp_int;
              
              ESP_LOGI("Vevor_8kW_BLE", "Setting Heater Temperature to %d°C", temp_int);
    
              if (temp_int > 36) temp_int = 36;
              if (temp_int < 8) temp_int = 8;
              
              id(heater_set_target_value).execute(temp_int);

  #  Heater Specific
  - id: request_data
    then:
      - ble_client.ble_write:
          id: heater_ble
          service_uuid: ${service_uuid}
          characteristic_uuid: ${char_fff1_uuid}
          value: [0xAA, 0x55, 0x0C, 0x22, 0x01, 0x00, 0x00, 0x2F]
      - delay: 200ms

  - id: set_heater_mode_temperature
    then:
      - if:
          condition:
            lambda: 'return id(heater_target_mode).state != "Temperature";'
          then:
            - lambda: |-
                ESP_LOGI("Vevor_8kW_BLE", "Setting Heater Target Mode to Temperature");
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: ${service_uuid}
                characteristic_uuid: ${char_fff1_uuid}
                value: [0xAA, 0x55, 0x0C, 0x22, 0x02, 0x02, 0x00, 0x32]
            - delay: 200ms

  - id: set_heater_mode_power
    then:
      - if:
          condition:
            lambda: 'return id(heater_target_mode).state != "Power";'
          then:
            - lambda: |-
                ESP_LOGI("Vevor_8kW_BLE", "Setting Heater Target Mode to Power");
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: ${service_uuid}
                characteristic_uuid: ${char_fff1_uuid}
                value: [0xAA, 0x55, 0x0C, 0x22, 0x02, 0x01, 0x00, 0x31]
            - delay: 200ms

  - id: heater_set_target_value
    parameters:
      x: int
    then:
      - if:
          condition:
            - lambda: |-
                return x != id(heater_setpoint);
          then:
            - lambda: |-
                ESP_LOGI("Vevor_8kW_BLE", "Setting Heater Setpoint to %d%", x);
            - ble_client.ble_write:
                id: heater_ble
                service_uuid: ${service_uuid}
                characteristic_uuid: ${char_fff1_uuid}
                value: !lambda |-
                  uint8_t y = (uint8_t) x;
                  uint8_t checksum =
                    ((0xAA + 0x55 + 0x0C + 0x22 + 0x04 + y + 0x00) + 1) % 256;
                  
                  return std::vector<uint8_t>{
                    0xAA, 0x55, 0x0C, 0x22,
                    0x04,
                    y,
                    0x00,
                    checksum
                  };
            - delay: 200ms

